FROM maven:3.6.3-openjdk-17-slim AS build_stage

WORKDIR /app_build

COPY pom.xml .

RUN mvn -e -B dependency:resolve
COPY src ./src

# Build the project and create the executable JAR
RUN mvn clean -e -B package -DskipTests