CREATE TABLE IF NOT EXISTS tbl_pengguna
(
    pengguna_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pengguna_nama        varchar(50)    DEFAULT NULL,
    pengguna_moto        varchar(100)   DEFAULT NULL,
    pengguna_jenkel      varchar(2)     DEFAULT NULL,
    pengguna_username    varchar(30)    DEFAULT NULL,
    pengguna_password    varchar(75)    DEFAULT NULL,
    pengguna_tentang     text,
    pengguna_email       varchar(50)    DEFAULT NULL,
    pengguna_nohp        varchar(20)    DEFAULT NULL,
    pengguna_facebook    varchar(50)    DEFAULT NULL,
    pengguna_twitter     varchar(50)    DEFAULT NULL,
    pengguna_linkedin    varchar(50)    DEFAULT NULL,
    pengguna_google_plus varchar(50)    DEFAULT NULL,
    pengguna_status      int            DEFAULT '1',
    pengguna_level       varchar(3)     DEFAULT NULL,
    pengguna_register    timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    pengguna_photo       varchar(40)    DEFAULT NULL,
    pengguna_active      boolean,
    PRIMARY KEY (pengguna_id)
);

CREATE TABLE IF NOT EXISTS role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    role varchar(25),
    PRIMARY KEY (id)
);

CREATE TABLE tbl_pengguna_roles
(
    user_id BIGINT NOT NULL,
    role_id bigint NOT NULL
);

ALTER TABLE tbl_pengguna_roles
    ADD CONSTRAINT FKrhfovtciq1l558cw6udg0h0d3 FOREIGN KEY (role_id) REFERENCES role (id);
ALTER TABLE tbl_pengguna_roles
    ADD CONSTRAINT FK55itppkw3i07do3h7qoclqd4k FOREIGN KEY (user_id) REFERENCES tbl_pengguna (pengguna_id);

--
-- Dumping data untuk tabel tbl_pengguna
--

INSERT INTO tbl_pengguna (pengguna_id, pengguna_nama, pengguna_moto, pengguna_jenkel, pengguna_username,
                          pengguna_password,
                          pengguna_tentang, pengguna_email, pengguna_nohp, pengguna_facebook, pengguna_twitter,
                          pengguna_linkedin, pengguna_google_plus, pengguna_status, pengguna_level, pengguna_register,
                          pengguna_photo, pengguna_active)
VALUES (1, 'Hendi Santika', 'Just do it', 'L', 'admin', '$2a$06$KdPmlUQcRaOM1177wRdgCuqMsaUE0pff7nmTV.exVLIyIKL7GcBmO',
        'I am a mountainner. to me mountainerring is a life', 'hendisantika@yahoo.co.id', '081277159401',
        'https://www.facebook.com/hendisantika/', 'twitter.com/hendisantika34', '', '', 1, '1', '2016-09-03 06:07:55',
        'db5dec647062751f2fb236b9bc3f1c54.png', TRUE),
       (2, 'Uzumaki Naruto', 'Just do it', 'L', 'user', '$2a$06$KdPmlUQcRaOM1177wRdgCuqMsaUE0pff7nmTV.exVLIyIKL7GcBmO',
        'I am a mountainner. to me mountainerring is a life', 'uzumaki_naruto@konohgakure.co.jp', '081277159401',
        'https://www.facebook.com/narutoofficialsns', 'twitter.com/naruto', '', '', 1, '1', '2016-09-03 06:07:55',
        'db5dec647062751f2fb236b9bc3f1c54.png', TRUE);

-- --------------------------------------------------------

-- Dumping data untuk tabel tbl_role
--
INSERT INTO role (id, role)
VALUES (1, 'ADMIN'),
       (2, 'USER');

-- --------------------------------------------------------
-- Dumping data untuk tabel tbl_user_role
--
INSERT INTO tbl_pengguna_roles (user_id, role_id)
VALUES (1, 1),
       (2, 2);

-- --------------------------------------------------------
