CREATE TABLE IF NOT EXISTS tbl_pengguna
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fullname     varchar(50)    DEFAULT NULL,
    moto         varchar(100)   DEFAULT NULL,
    jenkel       varchar(2)     DEFAULT NULL,
    username     varchar(30)    DEFAULT NULL,
    password     varchar(75)    DEFAULT NULL,
    tentang      text,
    email        varchar(50)    DEFAULT NULL,
    nohp         varchar(20)    DEFAULT NULL,
    facebook     varchar(50)    DEFAULT NULL,
    twitter      varchar(50)    DEFAULT NULL,
    linkedin     varchar(50)    DEFAULT NULL,
    status       int            DEFAULT '1',
    level        varchar(3)     DEFAULT NULL,
    register     timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    photo        varchar(40)    DEFAULT NULL,
    filename     varchar(40)    DEFAULT NULL,
    file_content bytea          DEFAULT NULL,
    active       boolean,
    created_by   varchar(50),
    created_on   timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by  varchar(50),
    modified_on  timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (email, username)
);

CREATE TABLE IF NOT EXISTS role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    role varchar(25),
    PRIMARY KEY (id)
);

CREATE TABLE tbl_pengguna_roles
(
    user_id BIGINT NOT NULL,
    role_id bigint NOT NULL
);

ALTER TABLE tbl_pengguna_roles
    ADD CONSTRAINT FKrhfovtciq1l558cw6udg0h0d3 FOREIGN KEY (role_id) REFERENCES role (id);
ALTER TABLE tbl_pengguna_roles
    ADD CONSTRAINT FK55itppkw3i07do3h7qoclqd4k FOREIGN KEY (user_id) REFERENCES tbl_pengguna (id);

--
-- Dumping data untuk tabel tbl_pengguna
--

INSERT INTO tbl_pengguna (id, fullname, moto, jenkel, username,
                          password,
                          tentang, email, nohp, facebook, twitter,
                          linkedin, status, level, register,
                          photo, active)
VALUES (1, 'Hendi Santika', 'Just do it', 'L', 'admin', '$2a$06$KdPmlUQcRaOM1177wRdgCuqMsaUE0pff7nmTV.exVLIyIKL7GcBmO',
        'I am a mountainner. to me mountainerring is a life', 'hendisantika@yahoo.co.id', '081277159401',
        'https://www.facebook.com/hendisantika/', 'twitter.com/hendisantika34', '', 1, '1', '2019-09-03 06:07:55',
        'db5dec647062751f2fb236b9bc3f1c54.png', TRUE),
       (2, 'Ismail Fajar', 'Just do it', 'L', 'fajar', '$2a$06$KdPmlUQcRaOM1177wRdgCuqMsaUE0pff7nmTV.exVLIyIKL7GcBmO',
        'I am a mountainner. to me mountainerring is a life', 'hendisantika@yahoo.co.id', '081277159401',
        'https://www.facebook.com/hendisantika/', 'twitter.com/hendisantika34', '', 1, '1', '2019-09-03 06:07:55',
        'db5dec647062751f2fb236b9bc3f1c54.png', TRUE),
       (3, 'Uzumaki Naruto', 'Just do it', 'L', 'user', '$2a$06$KdPmlUQcRaOM1177wRdgCuqMsaUE0pff7nmTV.exVLIyIKL7GcBmO',
        'I am a mountainner. to me mountainerring is a life', 'uzumaki_naruto@konohgakure.co.jp', '081277159401',
        'https://www.facebook.com/narutoofficialsns', 'twitter.com/naruto', '', 1, '1', '2019-09-03 06:07:55',
        'db5dec647062751f2fb236b9bc3f1c54.png', TRUE);

-- --------------------------------------------------------

-- Dumping data untuk tabel tbl_role
--
INSERT INTO role (id, role)
VALUES (1, 'ADMIN'),
       (2, 'USER');

-- --------------------------------------------------------
-- Dumping data untuk tabel tbl_user_role
--
INSERT INTO tbl_pengguna_roles (user_id, role_id)
VALUES (1, 1),
       (2, 1),
       (3, 2);

-- --------------------------------------------------------
