CREATE TABLE IF NOT EXISTS tbl_kategori
(
    id          int4 GENERATED BY DEFAULT AS IDENTITY,
    nama        varchar(30)    DEFAULT NULL,
    created_by  varchar(50),
    created_on  timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by varchar(50),
    modified_on timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

--
-- Dumping data untuk tabel tbl_kategori
--

INSERT INTO tbl_kategori (nama, created_on)
VALUES ('Pendidikan', '2019-09-06 05:49:04'),
       ('Politik', '2019-09-06 05:50:01'),
       ('Sains', '2019-09-06 05:59:39'),
       ('Penelitian', '2019-09-06 06:19:26'),
       ('Prestasi', '2019-09-07 02:51:09'),
       ('Olah Raga', '2019-01-13 13:20:31');

-- ------------------------------------------------